name: Michael Orenstein
favicon: null
layout_spectrum: 0.5736217047087848
typography_spectrum: 0.21186719019897282
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8678934171330184
  lightness: 0.10424536955542862
  saturation: 0.5559469216968864
  rhythmicContrast: 0.6038182976190001
purpose: []
